spring:
  application:
    name: prometheus
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, info'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true