server:
  port: 8081
spring:
  application:
    name: nacosServer
  config:
    import: optional:nacos:nacosServer
  cloud:
    nacos:
      config:
        server-addr: 192.168.31.201:8848
        file-extension: yaml
        username: nacos
        password: 123456
      discovery:
        server-addr: 192.168.31.201:8848
        username: nacos
        password: 123456