spring:
  application:
    name: kafka
  kafka:
    clientId: test
    bootstrap-servers:
      - 192.168.31.201:9092
      - 192.168.31.202:9092
      - 192.168.31.203:9092
    producer:
      keySerializer: org.apache.kafka.common.serialization.ByteArraySerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer